//! Tiny synthetic Phase-2 ONNX fixtures (inference-acceleration task 1.3, requirement 2.5).
//!
//! `tests/fixtures/phase2_tiny_{dynamic,fixed1}.onnx` are generated by
//! `tools/export/make_tiny_batch_onnx.py` (no trained weights). This file only checks that
//! both fixtures follow the production I/O contract and run through the existing CPU
//! single-window path; batched-vs-per-window equality lives in the batch inference tests.

use holter_analysis_assist::phase2::{
    ExecutionProviderKind, Phase2Model, WindowOutputs, INPUT_NAME, WINDOW_SAMPLES,
};
use ndarray::Array3;
use ort::session::Session;
use ort::value::{TensorRef, ValueType};
use std::path::PathBuf;

const DYNAMIC: &str = "phase2_tiny_dynamic.onnx";
const FIXED1: &str = "phase2_tiny_fixed1.onnx";

fn fixture(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
        .join(name)
}

fn ramp(scale: f32) -> Vec<f32> {
    (0..WINDOW_SAMPLES)
        .map(|i| scale * ((i as f32 / WINDOW_SAMPLES as f32) * 4.0 - 1.0))
        .collect()
}

fn run_cpu(name: &str, samples: &[f32]) -> WindowOutputs {
    let mut model = Phase2Model::load_with_provider(fixture(name), ExecutionProviderKind::Cpu)
        .unwrap_or_else(|e| panic!("load {name}: {e}"));
    assert_eq!(model.provider(), ExecutionProviderKind::Cpu);
    model
        .infer_window(samples)
        .unwrap_or_else(|e| panic!("infer_window {name}: {e}"))
}

fn assert_contract(name: &str, out: &WindowOutputs) {
    assert_eq!(out.beat.len(), WINDOW_SAMPLES, "{name}: beat length");
    assert_eq!(out.event.len(), WINDOW_SAMPLES, "{name}: event length");
    let in_unit = |v: f32| v.is_finite() && (0.0..=1.0).contains(&v);
    assert!(out.beat.iter().all(|&v| in_unit(v)), "{name}: beat range");
    assert!(
        out.event.iter().flatten().all(|&v| in_unit(v)),
        "{name}: event range"
    );
    assert!(in_unit(out.rhythm), "{name}: rhythm range");
}

fn tensor_dims(ty: &ValueType) -> Vec<i64> {
    ty.tensor_shape()
        .unwrap_or_else(|| panic!("expected tensor type, got {ty:?}"))
        .to_vec()
}

fn io_dims(name: &str) -> Vec<(String, Vec<i64>)> {
    let session = Session::builder()
        .expect("session builder")
        .commit_from_file(fixture(name))
        .unwrap_or_else(|e| panic!("open {name}: {e}"));
    session
        .inputs()
        .iter()
        .chain(session.outputs())
        .map(|o| (o.name().to_string(), tensor_dims(o.dtype())))
        .collect()
}

#[test]
fn fixtures_expose_production_io_names_and_batch_dims() {
    let expected = |batch: i64| {
        vec![
            (INPUT_NAME.to_string(), vec![batch, 10_000, 1]),
            ("beat".to_string(), vec![batch, 10_000, 1]),
            ("event".to_string(), vec![batch, 10_000, 3]),
            ("rhythm".to_string(), vec![batch, 1]),
        ]
    };
    assert_eq!(io_dims(DYNAMIC), expected(-1), "dynamic: symbolic batch");
    assert_eq!(io_dims(FIXED1), expected(1), "fixed1: batch fixed to 1");
}

#[test]
fn both_fixtures_load_and_run_existing_cpu_single_window_inference() {
    let samples = ramp(1.0);
    for name in [DYNAMIC, FIXED1] {
        let out = run_cpu(name, &samples);
        assert_contract(name, &out);
    }
}

#[test]
fn fixture_outputs_are_deterministic_and_depend_on_input() {
    for name in [DYNAMIC, FIXED1] {
        let a1 = run_cpu(name, &ramp(1.0));
        let a2 = run_cpu(name, &ramp(1.0));
        assert_eq!(a1.beat, a2.beat, "{name}: beat deterministic");
        assert_eq!(a1.event, a2.event, "{name}: event deterministic");
        assert_eq!(a1.rhythm, a2.rhythm, "{name}: rhythm deterministic");

        let b = run_cpu(name, &ramp(-0.5));
        assert_ne!(a1.beat, b.beat, "{name}: beat must depend on input");
        assert_ne!(a1.event, b.event, "{name}: event must depend on input");
        assert_ne!(a1.rhythm, b.rhythm, "{name}: rhythm must depend on input");

        let first = a1.beat[0];
        assert!(
            a1.beat.iter().any(|&v| v != first),
            "{name}: beat must vary per sample"
        );
        let e = a1.event[WINDOW_SAMPLES / 3];
        assert!(
            e[0] != e[1] && e[1] != e[2] && e[0] != e[2],
            "{name}: event channels must differ: {e:?}"
        );
    }
}

#[test]
fn dynamic_fixture_computes_each_batch_element_independently() {
    let scales = [1.0_f32, -0.5, 0.25];
    let mut flat = Vec::with_capacity(scales.len() * WINDOW_SAMPLES);
    for s in scales {
        flat.extend(ramp(s));
    }
    let input = Array3::from_shape_vec((scales.len(), WINDOW_SAMPLES, 1), flat).expect("shape");

    let mut session = Session::builder()
        .expect("session builder")
        .commit_from_file(fixture(DYNAMIC))
        .expect("open dynamic fixture");
    let outputs = session
        .run(ort::inputs![INPUT_NAME => TensorRef::from_array_view(&input).expect("input")])
        .expect("batched run");
    let extract = |name: &str| {
        let (shape, data) = outputs[name]
            .try_extract_tensor::<f32>()
            .unwrap_or_else(|e| panic!("extract {name}: {e}"));
        (shape.to_vec(), data.to_vec())
    };
    let (beat_shape, beat) = extract("beat");
    let (event_shape, event) = extract("event");
    let (rhythm_shape, rhythm) = extract("rhythm");
    assert_eq!(beat_shape, vec![3, 10_000, 1]);
    assert_eq!(event_shape, vec![3, 10_000, 3]);
    assert_eq!(rhythm_shape, vec![3, 1]);

    for (i, s) in scales.into_iter().enumerate() {
        let single = run_cpu(DYNAMIC, &ramp(s));
        let beat_i = &beat[i * WINDOW_SAMPLES..(i + 1) * WINDOW_SAMPLES];
        let event_i = &event[i * WINDOW_SAMPLES * 3..(i + 1) * WINDOW_SAMPLES * 3];
        assert_eq!(beat_i, single.beat.as_slice(), "batch[{i}] beat");
        assert_eq!(
            event_i,
            single.event.concat().as_slice(),
            "batch[{i}] event"
        );
        assert_eq!(rhythm[i], single.rhythm, "batch[{i}] rhythm");
    }
}

#[test]
fn dynamic_and_fixed1_fixtures_share_the_same_weights() {
    let samples = ramp(0.75);
    let dynamic = run_cpu(DYNAMIC, &samples);
    let fixed1 = run_cpu(FIXED1, &samples);
    assert_eq!(dynamic.beat, fixed1.beat);
    assert_eq!(dynamic.event, fixed1.event);
    assert_eq!(dynamic.rhythm, fixed1.rhythm);
}
